Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Max: 60

Style/MixinUsage:
  Enabled: false

AllCops:
  NewCops: enable
